version: "3"

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="test"
    ports:
      - 27017:27017
  postgres:
    image: postgres:12.2-alpine
    environment:
        POSTGRES_USER: app
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: app
    volumes:
        - api-postgres:/var/lib/postgresql/data
    ports:
        - "54321:5432"

volumes:
  api-postgres: