steps:
# Build docker image.
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/slack_bot_news:0.0.1', '.']

# Push docker image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/slack_bot_news']

# deploy to cloud run.
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 
      'app', 
      'deploy',
      'deploy/app.yaml',
      '--image-url', 'gcr.io/$PROJECT_ID/slack_bot_news:0.0.1'
    ]
timeout: "1600s"